### ISSUE TITLE
Make a state machine design for dst software that is independant of perun contract versions.

### ISSUE THREAD

**Issue by manoranjith** [direct-state-transfer/dst-doc#11]
dst project implements [perun protocol](https://perun.network/) to do offchain transactions. Current version of [dst-go](https://github.com/direct-state-transfer/dst-go) uses [legacy contracts](https://github.com/PerunEthereum/Perun/tree/master/legacy/contracts).

The contracts are being developed further and [new versions](https://github.com/PerunEthereum/Perun/tree/master/contracts) are coming up. In near future, the dst-go project will have to be use these new versions. To provide a direction for this migration, a state machine design that can accommodate the workflows of both legacy and new versions needs to be created. The design should also be flexible to easily accommodate changes in contract that might come up in future.

The state machine design can be done in [UML](https://en.wikipedia.org/wiki/Unified_Modeling_Language) using [plantuml tool](http://plantuml.com/). PlantUML tools allows one to write a UML diagram as simple text file (see [here](http://plantuml.com/starting)), from which PNG, JPEG and such image files can be created. This will also enable the changes to be easily tracked using version control systems like git.

**Comment by anagha-ks** [comment]
First version of State machine diagrams have been added [here](https://github.com/boschresearch/dst-statemachine)

**Comment by manoranjith** [comment]
Issue closed, as it relates to the older implementation which is now archived on [legacy/master](https://github.com/direct-state-transfer/dst-go/tree/legacy/master)
