### ISSUE TITLE
Use SVG images in docs instead of converting them to PNG first

### ISSUE THREAD

**Issue by choeppler** [direct-state-transfer/dst-doc#6]
There are several SVG images (e.g. [sessionID_creation.svg](https://github.com/direct-state-transfer/dst-doc/blob/f076417cb28a715ac6048f4f839b9ebc681f0177/source/images/developer_guide/sessionID_creation.svg)) which have been converted to PNG format (e.g. [sessionID_creation.png](https://github.com/direct-state-transfer/dst-doc/blob/f076417cb28a715ac6048f4f839b9ebc681f0177/source/_generated/developer_guide/sessionID_creation.png)). And the latter are used in the docs. I'd propose to use the SVGs directly as this results in higher quality images in the html docs.

**Comment by manoranjith** [comment]
There is no specific reason using PNG format, so images in SVG format can be directly used. 
However, the SVG images have to properly resized / cropped before using.

**Comment by choeppler** [comment]
Ok. Thanks for clarification @manoranjith.

So, the task would be to 
- [ ] check all SVGs in `source/images/**` and crop if necessary, 
- [ ] use them in the docs instead of the PNG version from `source/_generated/**` and 
- [ ] remove the corresponding PNGs from the `source/_generated/**` folders.
